# Generated by Django 6.0.1 on 2026-01-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='书籍名称')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='现价')),
                ('img_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='书籍图片链接')),
                ('place', models.CharField(max_length=100, verbose_name='交易地点')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='stuti_app.account', verbose_name='发布用户')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('wechat_id', models.CharField(max_length=50, verbose_name='微信号')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stuti_app.account', verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
                'ordering': ['name'],
            },
        ),
    ]
