# Generated by Django 6.0.1 on 2026-01-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuti_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(help_text='用户登录的唯一标识，不可重复', max_length=50, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='account',
            field=models.ForeignKey(help_text='外键关联发布书籍的用户，删除用户时同步删除其发布的书籍', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='stuti_app.account', verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='book',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='书籍的出售价格，保留两位小数', max_digits=10, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img_url',
            field=models.CharField(blank=True, help_text='书籍封面/内页的URL，支持空值', max_length=500, null=True, verbose_name='书籍图片链接'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='书籍的官方定价，保留两位小数', max_digits=10, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='remarks',
            field=models.CharField(blank=True, help_text='书籍的新旧程度等信息', max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(help_text='一对一关联账户，删除账户时同步删除个人信息', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stuti_app.account', verbose_name='关联账户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号'),
        ),
    ]
