# Generated by Django 6.0.1 on 2026-01-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuti_app', '0002_profile_update_time_alter_account_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
